build update

diff --git a/share/bin/sander.PMF.in b/share/bin/sander.PMF.in
--- a/share/bin/sander.PMF.in
+++ b/share/bin/sander.PMF.in
@@ -4,8 +4,11 @@
 # sander - script that executes _sander.MPI in Infinity environment
 #
 # Required environment:
-#  INF_NCPU               - number of CPU used for job execution
-#  INF_NODEFILE           - file name with the list of nodes
+#  INF_NCPUS            - number of CPU used for job execution
+#  INF_MPIFILE          - file name with the list of nodes
+# 
+# Optional environment:
+#  INF_OPENMPI2_SPEC
 #
 # =============================================================================
 
@@ -13,28 +16,28 @@ PROGRAM_NAME="sander.PMF"
 
 # check required environment --------------------------------------------------
 
-if [ "$INF_NCPU" == "" ]; then
+if [ "$INF_NCPUS" == "" ]; then
     echo ""
     echo "ERROR: Unable to execute: $PROGRAM_NAME!"
     echo "       Number of processors is not provided!"
-    echo "       Set INF_NCPU variable or use Infinity system for job submition!"
+    echo "       Set INF_NCPUS variable or use Infinity system for job submition!"
     echo ""
     exit 1
 fi
 
-if [ "$INF_NCPU" -eq 1 ]; then
+if [ "$INF_NCPUS" -eq 1 ]; then
     echo ""
-    echo "ERROR: Unable to execute: $PROGRAM_NAME !"
-    echo "       Number of CPU (\'$INF_NCPU\') has to be greater than 1."
+    echo "ERROR: Unable to execute: $PROGRAM_NAME!"
+    echo "       Number of CPU (\'$INF_NCPUS\') has to be greater than 1."
     echo ""
     exit 1
 fi
 
-if ! [ -f "$INF_NODEFILE" ]; then
+if ! [ -f "$INF_MPIFILE" ]; then
     echo ""
     echo "ERROR: Unable to execute: $PROGRAM_NAME!"
     echo "       Node file does not exist!"
-    echo "       Set INF_NODEFILE variable!"
+    echo "       Set INF_MPIFILE variable!"
     echo ""
     exit 1
 fi
@@ -45,27 +48,27 @@ PROG=`type -p _sander.PMF.MPI`
 
 if [ -z "$PROG" ]; then
     echo ""
-    echo "ERROR: Unable to execute: $PROGRAM_NAME !"
-    echo "       Full path to sander.MPI is not known !"
+    echo "ERROR: Unable to execute: $PROGRAM_NAME!"
+    echo "       Full path to _sander.PMF.MPI is not known!"
     echo ""
     exit 1
 fi
 
 # initialize mpich environment ------------------------------------------------
 
-module add openmpi:1.4.3
+module add @OPENMPI_MODULE@
 
 if [ $? -ne 0 ]; then
     echo ""
-    echo " ERROR: Unable to execute: $PROGRAM_NAME !"
-    echo "        Module 'openmpi' is required !"
+    echo " ERROR: Unable to execute: $PROGRAM_NAME!"
+    echo "        Module '@OPENMPI_MODULE@' is required!"
     echo ""
     exit 1
 fi
 
 # start program ---------------------------------------------------------------
 
-mpiexec -machinefile $INF_NODEFILE -np $INF_NCPU $PROG $*
+mpirun $INF_OPENMPI2_SPEC -machinefile $INF_MPIFILE -np $INF_NCPUS $PROG $*
 
 EXIT_CODE=$?
 
