update for building outside of Infinity env

diff --git a/share/bin/sander.PMF.in b/share/bin/sander.PMF.in
--- a/share/bin/sander.PMF.in
+++ b/share/bin/sander.PMF.in
@@ -17,29 +17,12 @@ PROGRAM_NAME="sander.PMF"
 # check required environment --------------------------------------------------
 
 if [ "$INF_NCPUS" == "" ]; then
-    echo ""
-    echo "ERROR: Unable to execute: $PROGRAM_NAME!"
-    echo "       Number of processors is not provided!"
-    echo "       Set INF_NCPUS variable or use Infinity system for job submition!"
-    echo ""
-    exit 1
+    export INF_NCPUS=1
 fi
 
-if [ "$INF_NCPUS" -eq 1 ]; then
-    echo ""
-    echo "ERROR: Unable to execute: $PROGRAM_NAME!"
-    echo "       Number of CPU (\'$INF_NCPUS\') has to be greater than 1."
-    echo ""
-    exit 1
-fi
-
-if ! [ -f "$INF_MPIFILE" ]; then
-    echo ""
-    echo "ERROR: Unable to execute: $PROGRAM_NAME!"
-    echo "       Node file does not exist!"
-    echo "       Set INF_MPIFILE variable!"
-    echo ""
-    exit 1
+INF_MACHINEFILE=""
+if [ -f "$INF_MPIFILE" ]; then
+    INF_MACHINEFILE="-machinefile $INF_MPIFILE"
 fi
 
 # get program name with path --------------------------------------------------
@@ -54,21 +37,31 @@ if [ -z "$PROG" ]; then
     exit 1
 fi
 
-# initialize mpich environment ------------------------------------------------
+# initialize openmpi environment -----------------------------------------------
 
-module add @OPENMPI_MODULE@
+# add OpenMPI module if defined
+if type module &> /dev/null; then
+    module add @OPENMPI_MODULE@
+    if [ $? -ne 0 ]; then
+        echo ""
+        echo " ERROR: Unable to execute: $PROGRAM_NAME!"
+        echo "        Module '@OPENMPI_MODULE@' is required!"
+        echo ""
+        exit 1
+    fi
+fi
 
-if [ $? -ne 0 ]; then
+if ! type mpirun &> /dev/null; then
     echo ""
     echo " ERROR: Unable to execute: $PROGRAM_NAME!"
-    echo "        Module '@OPENMPI_MODULE@' is required!"
+    echo "        The mpirun program is required!"
     echo ""
-    exit 1
+    exit 1  
 fi
 
 # start program ---------------------------------------------------------------
 
-mpirun $INF_OPENMPI2_SPEC -machinefile $INF_MPIFILE -np $INF_NCPUS $PROG $*
+mpirun $INF_OPENMPI2_SPEC $INF_MACHINEFILE -np "$INF_NCPUS" "$PROG" $@
 
 EXIT_CODE=$?
 
